project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Rohit Batra, PhD"
  navbar:
    title: Rohit Batra, PhD
    right:
      - text: Publications
        href: publications.qmd
      - text: CV
        href: cv.qmd
      
format:
  html:
    fontcolor: "black"
    fontsize: "20px"
    theme: [cosmo, styles.scss]
    page-layout: full

