project:
  type: website

website:
  title: "Home"
  site-url: https://rohitbatra29.github.io/website/
  page-footer: "Rohit Batra, PhD"
  navbar:
    title: Rohit Batra, PhD
    right:
      - text: Publications
        href: publications.qmd
      - text: CV
        href: cv.qmd
      
format:
  html:
    output-ext: ""
    fontcolor: "black"
    fontsize: "20px"
    theme: [cosmo, styles.scss]
    page-layout: full

